# modified from https://github.com/live-clones/xdmf/blob/master/CMake/FindMPI4PY.cmake

IF(NOT NUMPY_INCLUDE_DIR)
    EXECUTE_PROCESS(COMMAND
      "${PYTHON_EXECUTABLE}" "-c" "import numpy as np; print(np.get_include())"
      OUTPUT_VARIABLE NUMPY_COMMAND_OUTPUT
      RESULT_VARIABLE NUMPY_COMMAND_RESULT
      OUTPUT_STRIP_TRAILING_WHITESPACE)
    IF(NOT NUMPY_COMMAND_RESULT AND NOT NUMPY_COMMAND_OUTPUT MATCHES "Traceback")
        SET(NUMPY_INCLUDE_DIR ${NUMPY_COMMAND_OUTPUT} CACHE STRING "numpy include path")
    ENDIF()
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NumPy DEFAULT_MSG NUMPY_INCLUDE_DIRS)
